$(document).ready(function(){
	var $output = $('#output');
	// Original menu click event.
	$('.startgroup-option').click(function(){
		var id = $(this).attr('id');
		if(id=='std'){			// Generate Standard template page without any content.
			var templateText = '<!DOCTYPE HTML>\n<html>\n'
							 + ' <head>\n'
							 + '  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n'
							 + '  <script type="text/javascript" src="js/script.js"></script>\n'
							 + '  <link rel="stylesheet" href="css/stylesheet.css"/>\n'
							 + '  <title>HTML5 Sample Page</title>\n'
							 + '  <!-- Page template generated by http://chalarangelo.github.io/htmltemplategenerator/index.html-->\n'
							 + ' </head>\n'
							 + ' <body>\n'
							 + ' </body>\n'
							 + '</html>\n';
			$output.text(templateText);
			$('#output-wrapper').toggleClass('hidden');
		}
		else if(id=='std-c'){	// Generate Standard template page with sample content.
			var templateText = '<!DOCTYPE HTML>\n<html>\n'
							 + ' <head>\n'
							 + '  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n'
							 + '  <script type="text/javascript" src="js/script.js"></script>\n'
							 + '  <link rel="stylesheet" href="css/stylesheet.css"/>\n'
							 + '  <title>HTML5 Sample Page</title>\n'
							 + '  <!-- Page template generated by http://chalarangelo.github.io/htmltemplategenerator/index.html-->\n'
							 + ' </head>\n'
							 + ' <body>\n'
							 + '  <h1>This is a sample title</h1>\n'
							 + '  <h2>This is a sample subtitle</h2><br>\n'
							 + '  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent est mi, commodo vitae mauris at, sagittis vehicula sem. Quisque malesuada dui at justo maximus, vel placerat nibh blandit. Phasellus quis ipsum aliquam, fringilla ante sit amet, sagittis magna. In at dignissim eros, id vulputate tellus. Quisque orci urna, pretium in porttitor et, rhoncus in nulla. Aenean viverra ante in velit tincidunt, sit amet tincidunt ante suscipit. In malesuada consectetur molestie.</p><br>\n'
							 + '  <img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"><br>\n'
							 + '  <hr><br>\n'
							 + '  <ul>\n'
							 + '   <li>Suspendisse convallis ac metus non efficitur.</li>\n'
							 + '   <li>Donec consectetur eu nisi luctus bibendum.</li>\n'
							 + '   <li>Nam tempor facilisis sem vitae mattis.</li>\n'
							 + '   <li>Fusce feugiat rhoncus eros, id auctor mauris facilisis quis.</li>\n'
							 + '  </ul><br>\n'
							 + '  <div>Etiam maximus, ante vitae porttitor tincidunt, sem erat pharetra turpis, a ornare tortor purus <a href="https://www.google.com">ut justo</a>.</div><br>\n'				 
							 + '  <button type="button">Click Me!</button>\n'
							 + ' </body>\n'
							 + '</html>\n';
			$output.text(templateText);
			$('#output-wrapper').toggleClass('hidden');
		}
		else if(id=='std-cs'){	// Generate Standard template page with full content showcase.
			var templateText = '<!DOCTYPE HTML>\n<html>\n'
							 + ' <head>\n'
							 + '  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n'
							 + '  <script type="text/javascript" src="js/script.js"></script>\n'
							 + '  <link rel="stylesheet" href="css/stylesheet.css"/>\n'
							 + '  <title>HTML5 Sample Page</title>\n'
							 + '  <!-- Page template generated by http://chalarangelo.github.io/htmltemplategenerator/index.html-->\n'
							 + ' </head>\n'
							 + ' <body>\n'
							 + '  <h1>This is a sample title</h1>\n'
							 + '  <h2>This is a sample subtitle</h2><br>\n'
							 + '  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent est mi, commodo vitae mauris at, sagittis vehicula sem. Quisque malesuada dui at justo maximus, vel placerat nibh blandit. Phasellus quis ipsum aliquam, fringilla ante sit amet, sagittis magna. In at dignissim eros, id vulputate tellus. Quisque orci urna, pretium in porttitor et, rhoncus in nulla. Aenean viverra ante in velit tincidunt, sit amet tincidunt ante suscipit. In malesuada consectetur molestie.</p><br>\n'
							 + '  <img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"><br>\n'
							 + '  <hr><br>\n'
							 + '  <ol>\n'
							 + '   <li>First</li>\n'
							 + '   <li>Second</li>\n'
							 + '   <li>Third</li>\n'
							 + '  </ol>\n'
							 + '  <code>Ut sollicitudin arcu arcu, eget fermentum sem ullamcorper in.\n'
							 + '   Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n'
							 + '   Phasellus nec nisl nunc. Sed sit amet urna arcu.\n'
							 + '   Donec non consequat tortor, id fermentum felis.\n'
							 + '   Quisque elementum hendrerit egestas. In id rhoncus neque, eget mattis neque.\n'
							 + '   Suspendisse varius turpis et dui viverra semper. </code>\n'
							 + '  <hr><br>\n'
							 + '  <h3>This is another title</h3>\n'
							 + '  <form action="demo_form.asp" method="get">\n'
							 + '   First name: <input type="text" name="fname"><br>\n'
							 + '   Last name: <input type="text" name="lname"><br>\n'
							 + '   <input type="submit" value="Submit">\n'
							 + '  </form>\n'
							 + '  <h4>And another title</h4>\n'
							 + '  <table>\n'
  							 + '   <tr>\n'
    						 + '    <th>Month</th>\n'
    						 + '    <th>Savings</th>\n'
  							 + '   </tr>\n'
  							 + '   <tr>\n'
    						 + '    <td>January</td>\n'
    						 + '    <td>$100</td>\n'
  							 + '   </tr>\n'
  							 + '  </table> \n'			 
							 + '  <h5>One more title</h5>\n'
							 + '  <textarea rows="4" cols="50">\n'
							 + '   This text is a sample for the textarea.\n'
							 + '  </textarea>\n'
							 + '  <h6>And this is the last one of the titles</h6>\n'
							 + '  <ul>\n'
							 + '   <li>Suspendisse convallis ac metus non efficitur.</li>\n'
							 + '   <li>Donec consectetur eu nisi luctus bibendum.</li>\n'
							 + '   <li>Nam tempor facilisis sem vitae mattis.</li>\n'
							 + '   <li>Fusce feugiat rhoncus eros, id auctor mauris facilisis quis.</li>\n'
							 + '  </ul><br>\n'
							 + '  <div>Etiam maximus, ante vitae porttitor tincidunt, sem erat pharetra turpis, a ornare tortor purus <a href="https://www.google.com">ut justo</a>.</div><br>\n'				 
							 + '  <button type="button">Click Me!</button>\n'
							 + '  <blockquote cite="https://www.google.com">Nam non diam ante. Curabitur non enim vitae eros luctus porta.</blockquote><br><br>\n'
							 + ' </body>\n'
							 + '</html>\n';
			$output.text(templateText);
			$('#output-wrapper').toggleClass('hidden');
		}
		else{					// Show next menu...
			$output.text('COMING SOON...');
			$('#output-wrapper').toggleClass('hidden');
		}
	});


	// $('#output').text('<!DOCTYPE HTML>\n<html>\n');
	// $('#output').append(document.createTextNode(' <head>\n'));
	// $('#output').append(document.createTextNode('  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n'));
	// $('#output').append(document.createTextNode('  <link rel="stylesheet" href="style.css"/>\n'));
	// $('#output').append(document.createTextNode('  <script type="text/javascript" src="script.js"></script>\n'));
	// $('#output').append(document.createTextNode('  <title>HTML5 Sample Page</title>\n'));
	// $('#output').append(document.createTextNode(' </head>\n'));
	// $('#output').append(document.createTextNode(' <body>\n'));
	// $('#output').append(document.createTextNode(' </body>\n'));
	// $('#output').append(document.createTextNode('</html>\n'));

	// Close the output wrapper, reload the page.
	$('.fa-times').click(function(){
		location.reload();
	});
	// Copy the text from the output area to the clipboard.
	$('.fa-clipboard').click(function(){
		var copyTextarea = document.querySelector('#output');
  		copyTextarea.select();
		document.execCommand('copy');
	});
	// Open new tab/window with the project's github on footer click.
	$('#footer').click(function(){
		window.open('https://github.com/chalarangelo/htmltemplategenerator', '_blank');
	});
	// Highlight footer on hover.
	$('#footer').hover(
		function(){
			$('.fa-github').removeClass('fa-github').addClass('fa-arrow-circle-down');
		},
		function(){
			$('.fa-arrow-circle-down').removeClass('fa-arrow-circle-down').addClass('fa-github');
		});
});